name: progress-pulse-plugin
author: "H3nriqueL1ma"
version: 'alpha-v0.0.1'
description: "A plugin that adds a progression system by level of actions such as mining, combat, building, and many others."
main: com.github.h3nriquel1ma.progressPulsePlugin.ProgressPulsePlugin
api-version: '1.18'
